name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Pull Juice Shop Docker Image
      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      # Step 4: Start the Juice Shop Container
      - name: Start the Docker Container
        run: |
          docker run -d --name juice-shop-container -p 3000:3000 bkimminich/juice-shop

       # Step: Static Application Security Testing (SAST) using CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
              # Step: Software Composition Analysis (SCA)
      - name: Install Java
        run: sudo apt-get install -y default-jre

      - name: Install OWASP Dependency-Check
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip -q dependency-check-8.4.0-release.zip -d dependency-check
          ls -la dependency-check # Debugging step to confirm contents

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
          --project JuiceShop \
          --scan . \
          --format HTML \
          --out dependency-check-report

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html


