name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Pull Juice Shop Docker Image
      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      # Step 4: Start the Juice Shop Container
      - name: Start the Docker Container
        run: |
          docker run -d --name juice-shop-container -p 3000:3000 bkimminich/juice-shop

       # Step: Static Application Security Testing (SAST) using CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
              # Step: Software Composition Analysis (SCA)
                   
      - name: Dependency Check  
        uses: dependency-check/Dependency-Check_Action@1.1.0
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: workflows/reports


