name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop
      - name: Deploy to Environment
        run: |
            docker run -d --name juice-shop-container -p 3000:3000 bkimminich/juice-shop
     
      # Step 5: Run Tests inside the Docker Container
      - name: Run Tests in Container
        run: |
          docker exec juice-shop-container npm install
          docker exec juice-shop-container npm test 
    

                
